package com.myringle.blog.mapper;

import com.myringle.blog.pojo.TbUser;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Oct 27 11:14:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Oct 27 11:14:49 CST 2019
     */
    int insert(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Oct 27 11:14:49 CST 2019
     */
    int insertSelective(TbUser record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Oct 27 11:14:49 CST 2019
     */
    TbUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Oct 27 11:14:49 CST 2019
     */
    int updateByPrimaryKeySelective(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Oct 27 11:14:49 CST 2019
     */
    int updateByPrimaryKey(TbUser record);


    TbUser login(@Param("username") String username, @Param("password") String password);

    Integer selectCount(@Param("username") String  username);
}